line-length = 88
exclude = ["traceml/vendor"]

[lint.isort]
known-first-party = ["polyaxon", "traceml", "hypertune", "vents"]
known-third-party = ["rest_framework", "scipy", "sklearn", "datadog", "docker", "corsheaders", "celery", "picklefield", "sentry_sdk", "orjson", "pydantic", "clipped"]
extra-standard-library = ["typing", "typing_extensions", "mock", "pytest", "factory", "faker", "flaky", "numpy", "pandas", "requests", "websocket", "jinja2", "yaml", "pytz"]
force-single-line = false
force-sort-within-sections = true
combine-as-imports = true
lines-after-imports = 2
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[lint.per-file-ignores]
# Do not enforce usage and import order rules in init files
"__init__.py" = ["E402", "F401", "F403", "I"]
